
# Etapa 1: Build

FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production



# Etapa 2: Producción

FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY . .

# Usuario no root por seguridad

RUN addgroup -g 1001 -S nodejs && \
  adduser -S nodejs -u 1001
USER nodejs
EXPOSE 3000

CMD ["npm", "start"]